### ISSUE TITLE
Usernames cannot start with numbers

### ISSUE THREAD

**Issue by jmealo** [SlateFoundation/slate#120]

**Comment by themightychris** [comment]
This is intentional so that we can accept either username or ID number in some places (like URL slugs) and be able to discriminate between them easily. In schools that only want to use student ID as an identifier, we prefix the username like `sdp1234567`. The login form supports email, studentnumber, and username as identifiers (and it's pluggable to support any other unique identifiers a school might also attach to students) so those students can still login directly with their district ID number without worrying about what their username is.

**Comment by jmealo** [comment]
What does a URL slug have to do with a login username? It sounds like `Handle` has created a dependency hell scenario. I couldn't find any way to easily fix this issue which caused all student logins to silently fail.

Younger students don't have e-mail addresses so the ability to use a free-form string instead of an e-mail is the only reasonable solution other than decoupling completely unrelated data types. You can extend your classes to have a `to_url_slug()` or similar method to achieve the same thing without setting arbitrary restrictions on `TEXT` fields.

**Comment by themightychris** [comment]
Usernames are the URL slug for user accounts e.g. `/people/{username}` and we also support `/people/{ID}`, hence username can't look like `ID`. Sorry if that's inconvenient but it's already well-established and there's plenty of ways to do what you're trying to do without changing that.

Sorry if I didn't make this explicit enough, but StudentNumber is already a built-in field you can login with, so if you have a number that identifies students that you want them to login with just put it in there.

I don't know what dependency hell you're talking about...there's one class in charge of making things into slugs. Also not sure what you mean by making restrictions on `TEXT` fields.

If you need a numeric login, ignore the Username field and it'll autogenerate based on the `User::$usernameGenerator` setting, or you can populate username with some prefixed number like `sdp{studentid}`. Then you can put your number somewhere else, there's already the `StudentNumber` field that can be logged in with, or if your login number isn't the official student ID you can configure an additional field via a `php-config` file and add a custom user finder to enable login via that field

Here's an example `php-config` file that demonstrates a couple of these things, it could be placed at `php-config/Emergence/People/User.config.d/usernames.php` to activate (the filename portion can be anything, all files under `php-config/Emergence/People/User.config.d` will be executed to statically configure the User class):

```php
<?php

use Emergence\People\User;

User::$fields['LegacyUsername'] = [
    'default' => null
];

User::$usernameGenerator = [
    'suffixFormat' => '%s-%u',
    'format' => function (User $User, array $options) {
        $firstNameLength = 1;
        $middleNameLength = 0;

        do {
            $username = mb_substr($User->FirstName, 0, $firstNameLength, 'utf-8');
            $username .= mb_substr($User->MiddleName, 0, $middleNameLength, 'utf-8');
            $username .= $User->LastName;

            $username = preg_replace('/\PL/u', '', $username);

            if ($User->GraduationYear) {
                $username .= substr($User->GraduationYear, -2);
            }

            $username = HandleBehavior::transformText($username, ['lower' => true, 'transliterate' => true]);

            if (!User::getByWhere(array_merge($options['domainConstraints'], ['Username' => $username]))) {
                break;
            }

            if ($middleNameLength < mb_strlen($User->MiddleName, 'utf-8')) {
                $middleNameLength++;
            } elseif ($firstNameLength < mb_strlen($User->FirstName, 'utf-8')) {
                $firstNameLength++;
            } else {
                break;
            }
        } while (true);

        return $username;
    }
];

User::$fallbackUserFinders['LegacyUsername'] = function($username) {
    return User::getByField('LegacyUsername', $username);
};
```
This example shows how to do three things:
- Add a field called `LegacyUsername` to the users table
- Define an entirely custom `Username` generator (the `$usernameGenerator` option also supports the strings `'flast'`, `'firstl'`, and `'first.last'` to chose one of the built-in generators with `'flast'` being the default)
- Enable login via `LegacyUsername` values

**Comment by jmealo** [comment]
If you import users directly into MySQL without using the ORM and end up with numeric usernames the system white screens on login for those users. This should be a database constraint as it causes a compete failure.

Requiring schools to monkey patch code for configuration changes can be dangerous as a missing semicolon can cause the Emergence Editor to fail requiring manually using SQL to rollback the VFS causing a production outage that requires developer intervention.

**Comment by themightychris** [comment]
Good points, but importing users directly into mysql isn't officially supported. You can do it if you want, but don't put numbers for usernames.

Allowing code for configuration is a desired feature. A way to push/edit code that doesn't depend on the app layer is in the roadmap and the desired solution to the risks.

This isn't monkey-patching, procedural modification from php-config scripts is the intended use of `public static` class properties.

**Comment by jmealo** [comment]
Re: Dependency hell in this context is when a minor oversight in a base class forces K-12 schools to patch/edit core files to achieve correct/expected behavior. Since the core  components also power the compulsory editor/webdav interface it's never safe to edit these files in place without direct database access and knowledge of the VFS to rollback changes.

Complex changes to multiple core files cannot be achieved as they'd need to be committed in a database transaction to the VFS in order to avoid locking out the developer (PHP croaks due to a partially applied change).

This means that basic configuration changes that most schools need by default now requires use of a staging site and direct access to you for consulting.

This is dependency hell because the code depends on the developer being you or reading the entire code base and knowing how it will compose as the VFS doesn't support attaching a debugger and the code cannot be run locally.

**Comment by themightychris** [comment]
This isn't a minor oversight in a base class, it's an intentional aspect of Slate's URL structure

Also, like I said:

> A way to push/edit code that doesn't depend on the app layer is in the roadmap and the desired solution to the risks.

This renders most points moot

Supporting plugging callable code into certain configuration options is desirable and staying. Staging sites as a best practice is staying. Tools to push code via git and edit via WebDAV that can't be broken by app code is needed. Eliminating the SQL-based VFS is needed, compositing should be done in git. With those, running locally and debugging on a Linux machine is supported. Running locally on Macs is not a high-priority goal but is theoretically Not That Hard at that point if `habitat` gets to a place where it can deliver parity native mac builds for all dependencies.
