### ISSUE TITLE
Help installing Slate

### ISSUE THREAD

**Issue by jj4111** [SlateFoundation/slate#178]
I need some help installing Slate. This is on a windows server. I've been following the readme at https://github.com/SlateFoundation/slate. I've followed all the steps and when I get to the section to Run and Edit Slate the commands don't work. I type in start-all-local and I get the error that 'bash: start-all-local: command not found'. It's the exact same issue with the watch-site command. From what I've been lead to believe with the readme Slate should start working once I run the command start-all-local to start the habitat services. I know next to nothing about Slate, Habitat, and Docker so any help would be greatly appreciated.

**Comment by themightychris** [comment]
Hi @jj4111 , it sounds like when you ran `start-all-local` you either weren't inside a Habitat studio shell or your Habitat studio shell didn't run Slate's [`.studiorc`](https://github.com/SlateFoundation/slate/blob/develop/.studiorc) script.

Make sure you're entering the Habitat studio from the main directory of the Slate repository, and that you have the `develop` branch checked out (**not master**).

Keep an eye out after you run `hab studio -D enter` for any errors. When you run that, it should be starting a Docker container and then running the `.studiorc` script in your current directory before dropping you into the studio shell. The `.studiorc` script prints near the very end of the startup process a bunch of messages about the commands it set up, including `start-all-local`. You should see those messages listing commands right above your prompt when it first comes up. If you don't see that, then check whether you've ended up inside the Docker shell or your normal Windows shell.

Sharing a screenshot of (some of) what's between `hab studio -D enter` and `start-all-local` not working might be helpful if you need further help

**Comment by jj4111** [comment]
Thank you, that got that part to go. I have another issue however. This time it's with the watch-site. When I run the watch-site command it seems to stop at cleaning tree. That is when I noticed that windows machines need's a work around. So I then opened another power shell window and ran the docker-volume-watcher. I get the following error: WARNING:root:Bind of container admiring_williams was skipped since it has invalid source path /var/run/docker.sock 

It seems be wanting to look for a linux path which is why there is an error.

As a side note I had to install Docker Desktop because I couldn't get the daemon going otherwise . Not sure if that will affect anything so I'm letting it be known just in case.

**Comment by themightychris** [comment]
Are you sure it's not working at that point? Sounds like you might be able to just open http://localhost:7080 at that point and see it running

This Docker-based development process is new and we haven't put much work yet into making sure all the console output is clear and intuitive so I wouldn't be surprised if that was the only holdup

Re: the docker install, did the `choco install docker` command not take care of that for you? Thanks for any feedback on the Windows experience, it's not the primary platform for any of our developers so we need to hear about user experiences to improve it!

**Comment by jj4111** [comment]
At this point I get a localhost refused to connect error when I try http://localhost:7080 (or 2375 since the docker desktop app references that port as well). The choco install did install docker but the daemon was never initiated on it. I was never able to pull up a service for docker until I install the docker desktop. Are there any commands I can run to make sure everything is running?

**Comment by themightychris** [comment]
@jj4111 jump in our Gitter chat and maybe I can help, I'm gonna need to see some screen shots: https://gitter.im/SlateFoundation/slate

If I miss you, please share some screenshots of your terminal at various key points

**Comment by jj4111** [comment]
Here are some screenshots of the last few commands that i ran. If you want a more specific point then let me know.

![ScreenHunter 01](https://user-images.githubusercontent.com/48490277/54432107-42e95d80-46f6-11e9-80c2-6cc7d6ce9edb.png)
![ScreenHunter 02](https://user-images.githubusercontent.com/48490277/54432113-467ce480-46f6-11e9-844c-45e1e53d1218.png)
![ScreenHunter 03](https://user-images.githubusercontent.com/48490277/54432118-48df3e80-46f6-11e9-9f72-84ffd17e2fe9.png)
![ScreenHunter 04](https://user-images.githubusercontent.com/48490277/54432121-4b419880-46f6-11e9-890d-3946eed817d7.png)

**Comment by themightychris** [comment]
@jj4111 Ohh I think that '\r' thing is the issue. When I tested on windows I found the environment to be really peculiar about line breaks within the `.studiorc` file

Take a look at the history of that file, see if clearing out blank lines gets rid of that error: https://github.com/SlateFoundation/slate/commits/develop/.studiorc

**Comment by themightychris** [comment]
@jj4111 also, try running `update-site` instead of `watch-site` a few seconds after `start-all-local`

**Comment by jj4111** [comment]
That cleared those error's but new errors popped up. Since this is windows, do I need to run the watch-site before I run the docker-volume-watcher? Or do I just need the run the docker-volume-watcher by itself and do I need to make sure I run it from a certain directory?
![ScreenHunter 05](https://user-images.githubusercontent.com/48490277/54528889-49711280-494c-11e9-81a4-1bafb334e028.png)

**Comment by jj4111** [comment]
Is there any additional information or screenshot's you would like from me?

**Comment by themightychris** [comment]
@jj4111 you don't need any watcher stuff to work to get up and running, only to have changes you make after that get applied live. You can use `update-site` in place of `watch-site` to run a one-time update.

The way that Windows watcher workaround works though, it doesn't matter when you run docker-volume-watcher, just that it's active while you want watching to work

I've set up a Slack org we can use for community support, I think I'll need to get a closer look at your system to figure out what's going on. I'd really appreciate the chance to do a screen share so I can learn more about the sorts of hurdles Windows users are likely to encounter.

Register here for a Slack invitation: http://emergence.sh/connectors/slack/invite

**Comment by jj4111** [comment]
Can we schedule a time? I'm not sure what time zone you are in but my work day ends at 3 PM CST. So I won't be able to start a screen share with you right at this moment.

**Comment by themightychris** [comment]
@jj4111 go ahead and pick out a 30 minute session whenever works best for you: https://calendly.com/chrisalfano/30min
