### ISSUE TITLE
ensure that embedded fonts are being loaded optimally

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate#38]
Embedded fonts should be served up compiled into CSS files from SASS that get served up minified and individually like so:

```
{cssmin fonts/lato.css}
{cssmin fonts/fontawesome.css}
```

this ensures they are cached efficiently and have no availability issues.

We need to audit the new slate-theme and new Slate frontend design to ensure all fonts are being loaded this way and none are being loaded from public CDNs or multiple times.

**Comment by themightychris** [comment]
@ryon eliminated all the places we were loading fonts from CDN. These might be ok to use in the static index.html for SlateAdmin for local work but I want to make sure that when served up online from a Slate instance we're not loading anything from external CDNs. 

Check out this set of changes I made to switch back to using locally-served fonts:
- SlateFoundation/slate-admin@732a4300a8b112b5d601b881a3e8596f7adcbb0d
- SlateFoundation/slate-theme@d0b3d51a775a62a0d487f1bc50fba0cdc5ff127a
- SlateFoundation/slate@cc2b2db5a6a4368bae0d29887fdd4d1a7a538b98

Some things are looking different now:
![Before](https://cloud.githubusercontent.com/assets/458494/8270522/d52da478-17af-11e5-8822-fdc73ba7d8c8.png)
![After](https://cloud.githubusercontent.com/assets/458494/8270523/d79e22e6-17af-11e5-8897-aec91f6f19ad.png)

Seems like we're missing a weight or the font names aren't matching up. Review and update the stuff in these two trees to get our local fonts in order:
- https://github.com/SlateFoundation/slate/tree/development/site-root/sass/fonts
- https://github.com/SlateFoundation/slate/tree/development/site-root/fonts

**Comment by ryon** [comment]
I redid fonts in the slate-hq repo (and on http://slate-quarry-dev.sandbox01.jarv.us/)

**Comment by themightychris** [comment]
@ryon our lato.css build went from being 220KB with 6 faces embedded to 1.7MB with only 4 faces. Maybe you bumped it up from latin-only to the megapack?

**Comment by ryon** [comment]
I switched back to Latin-only but it still builds at 435 KB. Not sure how we got 220 for six faces before... that sounds really low. @themightychris 

3c26cc80ee2077a1e2b568622909c7183657d7ae

**Comment by themightychris** [comment]
@ryon I think I used some web tool to make a latin subset that stripped out some uncommon stuff. Also you might be looking at the pre-gzipped size whereas the 220 i cited was the gzipped size

**Comment by themightychris** [comment]
@ryon looks good now, can you commit the same changes to this repo (salte) ?

**Comment by ryon** [comment]
All done on salty @themightychris
