### ISSUE TITLE
Blog editor spacing error

### ISSUE THREAD

**Issue by ckunkel** [SlateFoundation/slate#40]
The Title bar should be justified to the left side of the edit box. The Tag box also does not align properly (it should fill the row). Also, when entering text in Markdown Text section, text is tabbed in and not justified to the left. 

![screen shot 2015-06-18 at 1 35 43 pm](https://cloud.githubusercontent.com/assets/5123794/8237713/3aee4b16-15bf-11e5-99f4-67b510ca451a.png)

**Comment by themightychris** [comment]
fixed in f3f47c0c37227f869f9900a385ba30184ecfb446
