### ISSUE TITLE
icons turned black after recent change

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate#48]
After updating compass to 1.0.3, or perhaps another recent SASS change that we didn't compile until now, the dashboard icons turned black (omnibar icons are still white though):

![screen shot 2015-06-25 at 11 42 21 pm](https://cloud.githubusercontent.com/assets/458494/8370301/f28aecf0-1b93-11e5-8d8b-8ba9259cda6b.png)

The color value is coming from: https://github.com/SlateFoundation/slate/blob/development/site-root/sass/slate/modules/_dashboard.scss#L20

which is `.dashboard-icon-bg { fill: $bg-color; }`

Maybe bg-color is set in multiple places and compass changed some precedence rules?

**Comment by ryon** [comment]
Addressed here d7f50d91ffae494daae19196cbe9e357c9ac055f

**Comment by themightychris** [comment]
looks good
