### ISSUE TITLE
Revert change to participants delete noun

### ISSUE THREAD

**Issue by themightychris** [SlateFoundation/slate#52]
Respond to comments in 89392a8955c2a640591b4273576632578e0f31a4 and revert the changes. What breaks when these changes get reverted?

**Comment by aharley40** [comment]
@themightychris I reverted my change in slate-admin as well as my change to the request handler.

**Comment by themightychris** [comment]
@aharley40 the fix for the CORS issue was already in emergence I just needed to update node0. Seems to work fine now with the DELETE verb
